"""initial_4

Revision ID: 841465b8fdb5
Revises: 5b9971f65c78
Create Date: 2026-04-20 22:33:32.714114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841465b8fdb5'
down_revision: Union[str, None] = '5b9971f65c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_history_scenario_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_scenario_id_fkey'), 'chat_history', 'scenarios', ['scenario_id'], ['id'])
    # ### end Alembic commands ###
